### PR TITLE
Battle record standardisation

### PR DESCRIPTION
**Pull request by Artifice**
Generals
Fix for idle general looping
Fix for pausing when trying to load a loudout that isn't set
Fix for saving loadout settings when loadouts are reset

Battle
Standardize all battle records to be stored in the battle.records. History is done for different effective attacks, either by using GB powers like Divine Favour or Confuse or by invading with different army sizes. Based on the success or failure, minimum and maximum effective defenses will be calculated for better win chance estimates. Before, if you succeeded at a Confusing a target, and then tried to duel the same target, CAAP would give you the same odds as if you never confused the target. Now it uses that information to give a better estimate of your chance to beat it.

GB
Fix for Rogue smokebomb attack
Streamlined DOM check for GB reviews, to reduce scanning time per page down to a third.
Remove user ID log spam, now that battle results are stored in the battle records, where they should be
Enable calculation for Divine Favour and Enrage based on % increase to stats

Other
Daylight savings offset changed for summer
Fix MyGuildId bug by moving the IDs into the caap.stats object
Records now strictly enforce templates, and fields not included in the templates are deleted instead of saved.
Added action for Essence work back into action list

### CODE REVIEW

**Comment by magowiz** [comment]
I found an issue : menu sidebar disappear in this version, could you please check it out ? I won't release in the meanwhile, so take your time.

**Comment by Artifice** [comment]
Thanks!


On Mon, Mar 9, 2015 at 12:10 AM, magowiz <notifications@github.com> wrote:

> I found an issue : menu sidebar disappear in this version, could you
> please check it out ? I won't release in the meanwhile, so take your time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magowiz/Castle-Age-Autoplayer/pull/202#issuecomment-77754450>
> .
>



-- 
- Crissman

To avoid this the XP community uses Refactoring. Refactoring is the term
used when improving the internal design of a system without changing the
external behaviour. Code Rot is the reverse of this, which I call
‘Refuctoring’.  -- *Dave Chaplin*
<http://www.byte-vision.com/ProductivityArticle.aspx>

**Comment by magowiz** [comment]
I also noticed an infinite loop : reviewing monsters -> fighting monsters -> conquesting players 
I saved a log, I will try to attach it on github someway (maybe in issue pages) .

**Comment by magowiz** [comment]
no way, only images can be attached here, could you please give me your email address in a private way ? i.e. using caap forum private message .... So I can send you the log I collected and if we are lucky it tracks down also what goes wrong with menu sidebar. Let me know .

**Comment by Artifice** [comment]
Just pushed a fix, thanks. Hopefully this will work better.

On Mon, Mar 9, 2015 at 2:42 PM, magowiz <notifications@github.com> wrote:

> no way, only images can be attached here, could you please give me your
> email address in a private way ? i.e. using caap forum private message ....
> So I can send you the log I collected and if we are lucky it tracks down
> also what goes wrong with menu sidebar. Let me know .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magowiz/Castle-Age-Autoplayer/pull/202#issuecomment-77803108>
> .
>



-- 
- Crissman

To avoid this the XP community uses Refactoring. Refactoring is the term
used when improving the internal design of a system without changing the
external behaviour. Code Rot is the reverse of this, which I call
‘Refuctoring’.  -- *Dave Chaplin*
<http://www.byte-vision.com/ProductivityArticle.aspx>

**Pull request merged**
