### PR TITLE
Recon fix

### PR DESCRIPTION
**Pull request by Artifice**
Fix recon score undefined.

### CODE REVIEW

**Comment by TheCoolDude** [comment]
If you need a hand to push commits thru,I would be more than happy to lend a hand.  I always keep a good eye on what is happening with CAAP.  I have experience using Github.  Just let me know.

**Comment by Artifice** [comment]
Thanks, CoolDude. Magowiz, have you had a chance to look at the latest
release? Can CoolDude help you release it?

On Tue, May 12, 2015 at 5:23 AM, TheCoolDude <notifications@github.com>
wrote:

> If you need a hand to push commits thru,I would be more than happy to lend
> a hand. I always keep a good eye on what is happening with CAAP. I have
> experience using Github. Just let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magowiz/Castle-Age-Autoplayer/pull/220#issuecomment-101036644>
> .
>



-- 
- Crissman

To avoid this the XP community uses Refactoring. Refactoring is the term
used when improving the internal design of a system without changing the
external behaviour. Code Rot is the reverse of this, which I call
‘Refuctoring’.  -- *Dave Chaplin*
<http://www.byte-vision.com/ProductivityArticle.aspx>

**Comment by magowiz** [comment]
sorry I missed this pull request :)

**Comment by magowiz** [comment]
this one makes menu sidebar disappear ..... no release for now..... I will provide log if needed .

**Pull request merged**
