### PR TITLE
Gifts

### PR DESCRIPTION
**Pull request by Artifice**

### CODE REVIEW

**Comment by magowiz** [comment]
Please check if I merged correctly, I clicked "merge branch" this time

**Comment by TheCoolDude** [comment]
It would seem it did not work.  Pull request is still showing.

**Comment by Artifice** [comment]
Yes, seems it's still open. Not sure how to fix from my end.

On Sun, Apr 5, 2015 at 2:12 AM, TheCoolDude <notifications@github.com>
wrote:

> It would seem it did not work.  Pull request is still showing.
>
> Sent from Type Mail
>
>
>
> On Apr 4, 2015, 13:33, at 13:33, magowiz <notifications@github.com> wrote:
> >Please check if I merged correctly, I clicked "merge branch" this time
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >
> https://github.com/magowiz/Castle-Age-Autoplayer/pull/214#issuecomment-89611417
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magowiz/Castle-Age-Autoplayer/pull/214#issuecomment-89615359>
> .
>



-- 
- Crissman

To avoid this the XP community uses Refactoring. Refactoring is the term
used when improving the internal design of a system without changing the
external behaviour. Code Rot is the reverse of this, which I call
‘Refuctoring’.  -- *Dave Chaplin*
<http://www.byte-vision.com/ProductivityArticle.aspx>

**Comment by TheCoolDude** [comment]
Maybe Undo the merge branch and merge the old fashion way.

**Comment by Artifice** [comment]
Thanks!

On Mon, Apr 6, 2015 at 4:21 PM, magowiz <notifications@github.com> wrote:

> Merged #214 <https://github.com/magowiz/Castle-Age-Autoplayer/pull/214>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magowiz/Castle-Age-Autoplayer/pull/214#event-273930359>
> .
>



-- 
- Crissman

To avoid this the XP community uses Refactoring. Refactoring is the term
used when improving the internal design of a system without changing the
external behaviour. Code Rot is the reverse of this, which I call
‘Refuctoring’.  -- *Dave Chaplin*
<http://www.byte-vision.com/ProductivityArticle.aspx>

**Pull request merged**
